apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend
  namespace: expense
  labels: 
    project: expense
    app: backend
    tier: backend
    version: blue
spec: 
  replicas: 1
  selector:
    matchLabels:
      project: expense
      app: backend
      tier: backend
      version: blue
  template:
    metadata: 
      labels: 
        project: expense
        app: backend
        tier: backend
        version: blue
    spec:
      containers:
      - name: backend
        image: lakshman143/backend:1.0.0


