kind: Service
apiVersion: v1 
metadata: 
  name: backend
  namespace: expense
spec:
  selector: 
    project: expense
    app: backend
    tier: backend
    version: green
  ports:
  - protocol: TCP
    targetPort: 8080
    port: 8080
  